use library;
select*from book;
update book set author_name='New_author_Name' where id in (1,4);
select count(author_awards) from book;
select * from book where page_number=(select min(page_number) from book);
select max(page_number) from book;
alter table book add price int;
update book set price=120 where id=1;
update book set price=300 where id=3;
update book set price=78 where id=4;
update book set price=40 where id=8;
update book set price=160 where id=10;
update book set price=99 where id=13;
update book set price=25 where id=17;
update book set price=52 where id=18;
update book set price=133 where id=23;
update book set price=90 where id=38;
select avg(price) from book;
select sum(price) from book where category='b-category';
select min(price) from book;
select*from book where price=(select min(price) from book);
select*from book where isbn like 'GW%';
select*from book where author_name like 'New%';
select*from book where publication_date like '____-05-__';
select*from book where price between 50 and 120;
select*from book where price not between 200 and 600;
delete from book where id=4;
delete from book where title='A title';
delete from book where isbn like 'GW%';
